# Generated by Django 5.0.6 on 2024-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tasks', '0002_remove_task_category_task_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
